<?php

/**
 * Implements hook_menu()
 */
function valghalla_lists_menu(){
  $items = array();

  $items['valghalla_lists'] = array(
    'title' => 'Valghalla Lister',
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'page callback' => 'system_admin_menu_block_page',
    'access callback' => array('user_is_logged_in'),
  );

  return $items;
}

/**
 * Implements hook_permission()
 */
function valghalla_lists_permission(){
  return array(
    'valghalla view messages list' => array(
      'title'=> t('Se "Beskeder" liste'),
    ),
    'valghalla view no-reply list' => array(
      'title'=> t('Se "Deltagere der endnu ikke har svaret" liste'),
    ),
    'valghalla view party-overview list' => array(
      'title'=> t('Se "Parti oversigt" liste'),
    ),
    'valghalla view no-email list' => array(
      'title'=> t('Se "Deltagere uden e-mail adresse" liste'),
    ),
  );
}
