<?php
/**
 * @file
 * liste_deltager.module
 */

/**
 * Implements hook_menu().
 */
function liste_deltager_menu() {
  $items['valghalla_lists/deltagere'] = array(
    'title' => 'Deltagerlister',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('liste_deltager_form'),
    'access arguments' => array('liste deltager see list'),
  );

  $saved_filters = variable_get('liste_deltager_saved_filters', array());

  foreach ($saved_filters as $id => $filter) {
    $items['valghalla_lists/gemt_liste-' . $id] = array(
      'title' => 'Gemt liste: ' . $filter['name'],
      'page callback' => 'drupal_goto',
      'page arguments' => array('valghalla_lists/deltagere/' . $id),
      'access arguments' => array('liste deltager see list'),
      'weight' => 100,
      'type' => MENU_NORMAL_ITEM,
    );
  }

  return $items;
}

/**
 * Implements hook_permission().
 */
function liste_deltager_permission() {
  return array(
    'liste deltager see list' => array(
      'title' => 'Se "Deltagerlister"',
      'description' => 'Dette tillader kun brugeren at se gemte lister',
    ),
    'liste deltager change filters' => array(
      'title' => 'Ændre filtre på "Deltagerlister"',
      'description' => 'Dette tillader brugeren at se gemte liste og skifte deres filtre',
    ),
    'liste deltager administer saved filters' => array(
      'title' => 'Gemme filtre på "Deltagerlister"',
      'description' => 'Dette tillader brugeren at se gemme filtre',
    ),
  );
}

/**
 * Form callback for "Deltager lister".
 */
function liste_deltager_form($form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'liste_deltager') . '/js/liste_deltager.js');

  $form['save_filters'] = array(
    '#type' => 'fieldset',
    '#title' => t('Gem filtre'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#prefix' => '<div class="no-print">',
    '#suffix' => '</div>',
    '#access' => user_access('liste deltager administer saved filters'),
  );

  $form['filter'] = array(
    '#access' => user_access('liste deltager change filters'),
  );

  // Filter volunteers.
  $form['filter']['polling_station'] = array(
    '#type' => 'select',
    '#multiple' => TRUE,
    '#size' => 8,
    '#title' => 'Valgsted',
    '#options' => liste_deltager_polling_station_options(),
    '#prefix' => '<div class="row no-print"><div class="col-xs-12">',
    '#suffix' => '<a class="js-select-all" href="#">Vælg alle</a></div>',
  );

  // Show columns.
  $form['filter']['columns'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Kolonner'),
    '#prefix' => '<div class="col-sm-6 col-md-3 no-print">',
    '#suffix' => '<a class="js-select-all" href="#">Vælg alle</a></div>',
    '#options' => _liste_deltager_columns(),
  );

  $form['filter']['roles'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Rolle(r)'),
    '#options' => odin_get_roles(),
    '#prefix' => '<div class="col-sm-6 col-md-3">',
    '#suffix' => '<a class="js-select-all" href="#">Vælg alle</a></div>',
  );

  $form['filter']['party'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Parti(er) (plads)'),
    '#prefix' => '<div class="col-sm-6 col-md-3">',
    '#suffix' => '<a class="js-select-all" href="#">Vælg alle</a></div>',
    '#options' => odin_get_parties(),
  );

  $form['filter']['rsvp'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Status'),
    '#options' => array(
      0 => 'Ikke besvaret',
      1 => 'Ja',
      2 => 'Nej',
      3 => 'Aldrig',
    ),
    '#prefix' => '<div class="col-sm-6 col-md-3">',
    '#suffix' => '<a class="js-select-all" href="#">Vælg alle</a></div></div>',
  );

  $saved_filters = variable_get('liste_deltager_saved_filters', array());
  $saved_filters_list = '<ul>';

  foreach ($saved_filters as $id => $filter) {
    $saved_filters_list .= '<li>' . l($filter['name'], 'valghalla_lists/deltagere/' . $id) . '</li>';
  }
  $saved_filters_list .= '</ul>';

  $form['save_filters']['filters'] = array(
    '#title' => 'Filtre',
    '#type' => 'item',
    '#markup' => $saved_filters_list,
  );

  $form['save_filters']['name'] = array(
    '#type' => 'textfield',
    '#title' => 'Navn på filter',
    '#suffix' => '<p><small>Opdateres navnet gemmes nyt filter med dette.</small></p>',
  );

  $form['save_filters']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Gem',
    '#submit' => array('liste_deltager_save_filter'),
    '#suffix' => '<p><small>Gem aktivkt filter.</small></p>',
  );

  $form['save_filters']['delete'] = array(
    '#type' => 'submit',
    '#value' => 'Slet',
    '#submit' => array('liste_deltager_delete_filter'),
    '#suffix' => '<p><small>Slet aktivt filter</small></p>',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#prefix' => '<div class="no-print">',
    '#value' => t('Opdater'),
    '#suffix' => '</div></div>',
  );

  // If a saved filters is selected. Fill out the forms default values.
  if (isset($saved_filters[arg(2)])) {
    $input = $saved_filters[arg(2)]['input'];
    $filter = $saved_filters[arg(2)];
    drupal_set_title('Gemt liste: ' . $filter['name']);

    $form['filter']['columns']['#default_value'] = $input['columns'];
    $form['filter']['polling_station']['#default_value'] = $input['polling_station'];
    $form['filter']['roles']['#default_value'] = $input['roles'];
    $form['filter']['party']['#default_value'] = $input['party'];
    $form['filter']['rsvp']['#default_value'] = $input['rsvp'];
    $form['save_filters']['name']['#default_value'] = $saved_filters[arg(2)]['name'];

    // And if it is not already rebuild (submitted), set the formstate values
    // and pretend that it is rebuild, to trigger an update of the results.
    if (!isset($form_state['rebuild']) || !$form_state['rebuild']) {
      $form_state['values'] = $input;
      $form_state['rebuild'] = TRUE;
    }
  }

  if (isset($form_state['rebuild']) && $form_state['rebuild']) {
    $form['print'] = array(
      '#type' => 'button',
      '#value' => t('Print'),
      '#attributes' => array('onclick' => 'javascript: window.print();'),
      '#prefix' => '<div class="no-print print-button">',
      '#suffix' => '</div>',
    );

    $form['results'] = array(
      '#markup' => liste_deltager_generate_list($form_state['values']),
    );
  }
  if (!$election_node = node_load($_SESSION['election_nid'])) {
    return array(array('#markup' => 'Du skal vælge et valg i dropdown menuen øverst.'));
  }

  return $form;
}

/**
 * Save filter callback.
 */
function liste_deltager_save_filter(&$form, &$form_state) {
  $id = strtolower(preg_replace("/[^A-Za-z0-9]/", '', $form_state['values']['name']));
  $name = $form_state['values']['name'];

  $saved_filters = variable_get('liste_deltager_saved_filters', array());

  $input = $form_state['input'];

  $saved_filters[$id]['name'] = $name;
  $saved_filters[$id]['input'] = $input;

  variable_set('liste_deltager_saved_filters', $saved_filters);
  menu_rebuild();
  drupal_goto('valghalla_lists/deltagere/' . $id);
}

/**
 * Delete filter callback.
 */
function liste_deltager_delete_filter(&$form, &$form_state) {
  $saved_filters = variable_get('liste_deltager_saved_filters', array());

  unset($saved_filters[arg(2)]);

  variable_set('liste_deltager_saved_filters', $saved_filters);
  menu_rebuild();
  drupal_goto('valghalla_lists/deltagere');
}
/**
 * Submit callback for "Delager lister".
 */
function liste_deltager_form_submit(&$form, &$form_state) {
  $form_state['rebuild'] = TRUE;
}

/**
 * Generate list of volunteers.
 */
function liste_deltager_generate_list($values) {
  $variables = array();

  if ($values['polling_station']) {
    $variables['header'] = liste_deltager_generate_header($values);

    foreach ($values['polling_station'] as $polling_station) {
      $_values = $values;
      $_values['polling_station'] = $polling_station;

      $variables['header'][$polling_station] = liste_deltager_generate_header($_values);

      $variables['table'][$polling_station] = liste_deltager_generate_table($_values);
    }
  }

  return theme('liste_deltager_list', $variables);
}

/**
 * Generate header for list.
 */
function liste_deltager_generate_header($values) {
  $header = array();

  if ($election = node_load($_SESSION['election_nid'])) {
    $header['election'] = $election->title;

    $election_date_field = field_get_items('node', $election, 'field_date');
    $header['date'] = strtolower(format_date(strtotime($election_date_field[0]['value']), 'custom', 'l, j. F, Y'));
  }

  if ($polling_station = node_load($values['polling_station'])) {
    $header['polling_station'] = $polling_station->title;
    $header['adress'] = valghalla_polling_station_get_adress($polling_station);

    if ($school_code_field = field_get_items('node', $polling_station, 'field_venue_skolekode')) {
      $header['schoolcode'] = $school_code_field[0]['value'];
    }

    $header['contact_info'] = valghalla_polling_station_get_contact($polling_station);
  }

  return $header;
}

/**
 * Generate table of volunteers.
 */
function liste_deltager_generate_table($values) {
  $header = array();
  $rows = array();

  $available_columns = _liste_deltager_columns();
  foreach ($values['columns'] as $column => $checked) {
    if ($checked) {
      $header[] = $available_columns[$column];
    }
  }

  foreach (liste_deltager_get_volunteers($values) as $key => $volunteer) {
    $rows[$key] = array();
    foreach ($values['columns'] as $column => $checked) {
      if ($checked) {
        $rows[$key][$column] = $volunteer[$column];
      }
    }
  }

  return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * Get a list of volunteers.
 */
function liste_deltager_get_volunteers($values) {
  // Prepare statement.
  $volunteer_query = new EntityFieldQuery();
  $volunteer_query->entityCondition('entity_type', 'field_collection_item')
      ->entityCondition('bundle', 'field_electioninfo');

  $roles = count($values['roles']) > 0 ? $values['roles'] : FALSE;
  $party_selected = $party = count($values['party']) > 0 ? $values['party'] : FALSE;

  $rsvp_filter = count($values['rsvp']) > 0 ? $values['rsvp'] : FALSE;
  $polling_station = count($values['polling_station']) > 0 ? $values['polling_station'] : FALSE;

  $rsvp_map = array(
    0 => '-',
    1 => 'Ja',
    2 => 'Nej',
    3 => 'Aldrig',
  );

  if ($_SESSION['election_nid']) {
    $volunteer_query->fieldCondition('field_election', 'target_id', $_SESSION['election_nid']);
  }
  if ($roles) {
    $volunteer_query->fieldCondition('field_post_role', 'target_id', $roles);
  }
  if ($party) {
    $volunteer_query->fieldCondition('field_post_party', 'target_id', $party);
  }

  if ($polling_station != 'none') {
    $volunteer_query->fieldCondition('field_vlnt_station', 'target_id', $polling_station);
  }
  $query_result = $volunteer_query->execute();

  $result       = array_keys(array_shift($query_result));

  $parties = odin_get_parties();
  $roles_array = odin_get_roles();

  if (db_table_exists('field_election_roles_diaet')) {
    $diet_rows = db_query("SELECT * FROM {field_election_roles_diaet} r WHERE r.nid = " . $_SESSION['election_nid'])->fetchObject();

    if (!is_null($diet_rows)) {
      $diet_data = unserialize($diet_rows->role_diaet_value);
    }

    foreach ($roles_array as $id => $role) {
      $diet_map[$role] = $diet_data[$id];
    }
  }

  $values = array();

  // Loop over results, get info for all columns.
  foreach ($result as $key => $fc_id) {
    $volunteer_fc = entity_load_single('field_collection_item', $fc_id);
    if (!is_object($volunteer_fc)) {
      continue;
    }
    // Sort out those who has a station set
    if ($polling_station == 'none') {
      if (!empty($volunteer_fc->field_vlnt_station)) {
        continue;
      }
    }

    $volunteer = $volunteer_fc->hostEntity();

    $party_post_field = field_get_items('field_collection_item', $volunteer_fc, 'field_post_party');
    $party_post = $parties[$party_post_field[0]['target_id']];

    $rsvp_field = field_get_items('field_collection_item', $volunteer_fc, 'field_rsvp');

    // If the field does not contain any content, set the field value to 0.
    if (!$rsvp_field) {
      $rsvp_field[0]['value'] = '0';
    }

    // The value of the volunteers response.
    $rsvp = $rsvp_map[$rsvp_field[0]['value']];

    if (!in_array($rsvp_field[0]['value'], $rsvp_filter, TRUE)) {
      continue;
    }

    $party_field = field_get_items('node', $volunteer, 'field_party');
    $party = $parties[$party_field[0]['tid']];

    $cpr_field = field_get_items('node', $volunteer, 'field_cpr_number');

    if (user_access('see all psn numbers')) {
      $cpr = $cpr_field[0]['value'];
    }
    else {
      $cpr = substr($cpr_field[0]['value'], 0, 6);
    }

    $tokens = _valghalla_helper_get_token_values($volunteer_fc);

    // Diet.
    $diet = $diet_map[$tokens['!position']];

    // If it's set on the fc item, use that. Otherwise we just keep
    // the value set on the election.
    if ($diaet_field = field_get_items('field_collection_item', $volunteer_fc, 'field_diaet')) {
      $diet = $diaet_field[0]['value'];
    }

    $age = _valghalla_helper_get_age_from_cpr($cpr);

    $values[$volunteer->nid] = array(
      'name' => $tokens['!name'],
      'role' => $tokens['!position'],
      'mail' => $tokens['!email'],
      'phone' => $tokens['!phone'],
      'rsvp' => $rsvp,
      'cpr' => $cpr,
      'age' => $age,
      'party' => $party,
      'party_post' => $party_post,
      'diet' => $diet,
      'sign' => '<div class="sign-col"></div>',
    );
  }
  // Get a table of people do not have a place.
  if ($polling_station == 'none') {

    // Add thoes volunteers that does not contains a place in a given election.
    $volunteer_fc_none_polling = liste_deltager_none_polling_station($_SESSION['election_nid'], $roles, $party_selected);
    foreach ($volunteer_fc_none_polling as $node) {
      $cpr_none_field = field_get_items('node', $node, 'field_cpr_number');

      if (user_access('see all psn numbers')) {

        $cpr_none = $cpr_none_field[0]['value'];
      }
      else {
        $cpr_none = substr($cpr_none_field[0]['value'], 0, 6);
      }
      $age_none = _valghalla_helper_get_age_from_cpr($cpr_none);
      $par_field = field_get_items('node', $node, 'field_party');
      $par_field = $parties[$par_field[0]['tid']];

      if (isset($values[$node->nid])) {
        continue;
      }
      if ($role_field = field_get_items('node', $node, 'field_rolle_id')) {
        $role_field_value = node_load($role_field[0]['nid'])->title;
      }
      $values[$node->nid] = array(
        'name' => $node->title,
        'role' => $role_field_value,
        'mail' => ($email_field = field_get_items('node', $node, 'field_email')) ? $email_field[0]['email'] : '',
        'phone' => ($telf_field = field_get_items('node', $node, 'field_phone')) ? $telf_field[0]['value'] : '',
        'rsvp' => '',
        'cpr' =>  $cpr_none,
        'age' => $age_none,
        'party' => $par_field,
        'party_post' => '',
        'diet' => '',
        'sign' => '<div class="sign-col"></div>',
      );
    }

  }
  return $values;
}
/**
 * Get all volunteers who do not have a place.
 */
function liste_deltager_none_polling_station($election_id, $roles, $party) {
  $type = "volunteers";

  $nodes = node_load_multiple(array(), array('type' => $type));

  $list = array();
  foreach($nodes as $node) {
    $none_polling_station = TRUE;
    $role_selected = TRUE;
    $party_selected = TRUE;
    if ($field = field_get_items('node', $node, 'field_electioninfo')) {
      foreach ($field as $field_item) {
        $volunteer_fc = field_collection_item_load($field_item['value']);
        $election = field_get_items('field_collection_item', $volunteer_fc, 'field_election');
        $polling_station = field_get_items('field_collection_item', $volunteer_fc, 'field_vlnt_station');
        $roles_field = field_get_items('field_collection_item', $volunteer_fc, 'field_post_role');
        $party_field = field_get_items('field_collection_item', $volunteer_fc, 'field_post_party');

        if ($election[0]['target_id'] == $election_id && $polling_station) {
          $none_polling_station = FALSE;
        }

        if ($roles_field && array_key_exists($roles_field[0]['target_id'], $roles)
            && !$roles[$roles_field[0]['target_id']]) {
          $role_selected = FALSE;
        }

        if ($party_field && array_key_exists($party_field[0]['target_id'], $party)
            && !$party[$party_field[0]['target_id']]) {
          $party_selected = FALSE;
        }
      }
      if ($none_polling_station && $role_selected && $party_selected) {
        $list[] = $node;
      }
    }
    // Does not contain fc.
    else {
      $node_role = field_get_items('node', $node, 'field_rolle_id');
      $node_party = field_get_items('node', $node, 'field_party');

      if ($node_role && array_key_exists($node_role[0]['nid'], $roles )
          && !$roles[$node_role[0]['nid']]){
        $role_selected = FALSE;
      }

      if ($node_party && array_key_exists($node_party[0]['tid'], $party)
          && !$party[$node_party[0]['tid']]) {
        $party_selected = FALSE;
      }

      if ($none_polling_station && $role_selected && $party_selected) {
        $list[] = $node;
      }
    }
  }
  return $list;
}
/**
 * Implements hook_theme().
 */
function liste_deltager_theme() {
  return array(
    'liste_deltager_list' => array(
      'template' => 'liste_deltager_list',
    ),
  );
}

/**
 * A list of columns that could be shown in the list.
 */
function _liste_deltager_columns() {
  return array(
    'name' => 'Navn',
    'cpr' => 'Cpr-nr.',
    'age' => 'Alder',
    'role' => 'Rolle',
    'rsvp' => 'RSVP',
    'phone' => 'Telefon',
    'mail' => 'Mail',
    'party' => 'Parti (deltager)',
    'party_post' => 'Parti (plads)',
    'diet' => 'Diæt',
    'sign' => 'Kvittering',
  );
}

/**
 * Generate list of polling stations.
 */
function liste_deltager_polling_station_options() {

  if (!$election_node = node_load($_SESSION['election_nid'])) {
    return array('Du skal vælge et valg i dropdown menuen øverst.');
  }

  // Use odin_get_polling_stations(), it will return a correctly sorted array
  // of polling stations.
  $polling_station_nids = odin_get_polling_stations($election_node->nid);
  $options = array();

  // No polling station
  $options[t('Intet valgsted')] = array('none' => t('Uden tilknytning til et valgsted'));

  foreach ($polling_station_nids as $polling_station_nid => $polling_station_title) {
    $polling_station = node_load($polling_station_nid);

    if ($constituency_field = field_get_items('node', $polling_station, 'field_constituency')) {
      // We save the data in 2 arrays, and don't populate options yet, as we
      // have to sort the options according to the title of the
      // constituencies.
      $constituency = node_load($constituency_field[0]['nid']);
      $constituencies[$constituency->nid] = $constituency->title;
      $polling_stations[$constituency->nid][$polling_station->nid] = $polling_station->title;
    }

    else {
      $options[$polling_station->nid] = $polling_station->title;
    }
  }

  if ($constituencies && $polling_stations) {
    natsort($constituencies);

    foreach ($constituencies as $constituency_nid => $constituency_title) {
      $options[$constituency_title] = $polling_stations[$constituency_nid];
    }
  }

  return $options;
}
